""" Provides definition of the tests in folly libarary. """

def folly_tests_def():
    return {
        "chrono/test/": [
            {
                "name": "chrono_conv_test",
                "srcs": ["ConvTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
        ],
        "compression/test/": [
            {"name": "compression_test", "srcs": ["CompressionTest.cpp"], "tags": ["SLOW"]},
        ],
        "container/test/": [
            {"name": "access_test", "srcs": ["AccessTest.cpp"]},
            {"name": "array_test", "srcs": ["ArrayTest.cpp"]},
            {
                "benchmark": 1,
                "name": "bit_iterator_benchmark",
                "srcs": ["BitIteratorBench.cpp"],
            },
            {"name": "bit_iterator_test", "srcs": ["BitIteratorTest.cpp"]},
            {"name": "enumerate_test", "srcs": ["EnumerateTest.cpp"]},
            {
                "benchmark": 1,
                "name": "evicting_cache_map_benchmark",
                "srcs": ["EvictingCacheMapBench.cpp"],
            },
            {"name": "evicting_cache_map_test", "srcs": ["EvictingCacheMapTest.cpp"]},
            {"name": "f14_fwd_test", "srcs": ["F14FwdTest.cpp"]},
            #
            # TODO(pkomlev): fix build
            #
            # {"name": "f14_map_test", "srcs": ["F14MapTest.cpp"]},
            {
                "name": "f14_set_test",
                "srcs": ["F14SetTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "heap_vector_types_test", "srcs": ["heap_vector_types_test.cpp"]},
            {"benchmark": 1, "name": "foreach_benchmark", "srcs": ["ForeachBenchmark.cpp"]},
            {"name": "foreach_test", "srcs": ["ForeachTest.cpp"]},
            {"name": "merge_test", "srcs": ["MergeTest.cpp"]},
            {
                "benchmark": 1,
                "name": "sparse_byte_set_benchmark",
                "srcs": ["SparseByteSetBenchmark.cpp"],
            },
            {"name": "sparse_byte_set_test", "srcs": ["SparseByteSetTest.cpp"]},
            {"name": "util_test", "srcs": ["UtilTest.cpp"]},
        ],
        "concurrency/test/": [
            {
                "name": "atomic_shared_ptr_test",
                "srcs": ["AtomicSharedPtrTest.cpp"],
                "hdrs": ["AtomicSharedPtrCounted.h"],
            },
            {
                "name": "cache_locality_test",
                "srcs": ["CacheLocalityTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "core_cached_shared_ptr_test",
                "srcs": ["CoreCachedSharedPtrTest.cpp"],
            },
            {
                "benchmark": 1,
                "name": "concurrent_hash_map_benchmark",
                "srcs": ["ConcurrentHashMapBench.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "concurrent_hash_map_test",
                "srcs": ["ConcurrentHashMapTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "dynamic_bounded_queue_test",
                "srcs": ["DynamicBoundedQueueTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "priority_unbounded_queue_set_test",
                "srcs": ["PriorityUnboundedQueueSetTest.cpp"],
            },
            {
                "benchmark": 1,
                "name": "thread_cached_synchronized_benchmark",
                "srcs": ["ThreadCachedSynchronizedBench.cpp"],
            },
            {
                "name": "thread_cached_synchronized_test",
                "srcs": ["ThreadCachedSynchronizedTest.cpp"],
            },
            {"name": "unbounded_queue_test", "srcs": ["UnboundedQueueTest.cpp"]},
        ],
        "detail/base64_detail/tests/": [
            {
                "name": "base64_detail_test",
                "srcs": [
                    "Base64AgainstScalarTest.cpp",
                    "Base64PlatformTest.cpp",
                    "Base64SpecialCasesTest.cpp",
                ],
            },
        ],
        "detail/test/": [
            {
                "name": "static_singleton_manager_test",
                "srcs": ["StaticSingletonManagerTest.cpp"],
            },
            {"name": "simd_for_each_test", "srcs": ["SimdForEachTest.cpp"]},
            {
                "name": "simple_simd_string_utils_test",
                "srcs": ["SimpleSimdStringUtilsTest.cpp"],
            },
            {"name": "split_string_simd_test", "srcs": ["SplitStringSimdTest.cpp"]},
            {"name": "unroll_utils_test", "srcs": ["UnrollUtilsTest.cpp"]},
        ],
        "executors/task_queue/test/": [
            {
                "name": "priority_unbounded_blocking_queue_test",
                "srcs": ["PriorityUnboundedBlockingQueueTest.cpp"],
            },
            {
                "benchmark": 1,
                "name": "unbounded_blocking_queue_benchmark",
                "srcs": ["UnboundedBlockingQueueBench.cpp"],
            },
            {
                "name": "unbounded_blocking_queue_test",
                "srcs": ["UnboundedBlockingQueueTest.cpp"],
            },
        ],
        "executors/test/": [
            {"name": "async_helpers_test", "srcs": ["AsyncTest.cpp"]},
            {"name": "codel_test", "srcs": ["CodelTest.cpp"], "tags": ["WINDOWS_DISABLED"]},
            {
                "benchmark": 1,
                "name": "edf_thread_pool_executor_benchmark",
                "srcs": ["EDFThreadPoolExecutorBenchmark.cpp"],
            },
            {"name": "executor_test", "srcs": ["ExecutorTest.cpp"]},
            {
                "name": "fiber_io_executor_test",
                "srcs": ["FiberIOExecutorTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "global_executor_test", "srcs": ["GlobalExecutorTest.cpp"]},
            {"name": "serial_executor_test", "srcs": ["SerialExecutorTest.cpp"]},
            {
                "name": "thread_pool_executor_test",
                "srcs": ["ThreadPoolExecutorTest.cpp"],
                "tags": ["BROKEN", "WINDOWS_DISABLED"],
            },
            {"name": "threaded_executor_test", "srcs": ["ThreadedExecutorTest.cpp"]},
            {
                "name": "timed_drivable_executor_test",
                "srcs": ["TimedDrivableExecutorTest.cpp"],
            },
        ],
        #
        # TODO(pkomlev): condition these on libsodium configured
        #
        # "experimental/crypto/test/": [
        #     {"name": "blake2xb_test", "srcs": ["Blake2xbTest.cpp"]},
        #     {"name": "lt_hash_test", "srcs": ["LtHashTest.cpp"]},
        # ],
        #
        # TODO(pkomlev): condition these on asyncio configured
        #
        # "experimental/io/test/": [
        #     {"name": "fs_util_test", "srcs": ["FsUtilTest.cpp"]},
        #     {
        #         "name": "async_io_test",
        #         "srcs": [
        #             "AsyncIOTest.cpp",
        #             "AsyncBaseTestLib.cpp",
        #             "IoTestTempFileUtil.cpp",
        #         ],
        #     },
        # ],
        "experimental/test/": [
            {"name": "autotimer_test", "srcs": ["AutoTimerTest.cpp"]},
            {"name": "bits_test_2", "srcs": ["BitsTest.cpp"]},
            {"name": "bitvector_test", "srcs": ["BitVectorCodingTest.cpp"]},
            {"name": "dynamic_parser_test", "srcs": ["DynamicParserTest.cpp"]},
            {"name": "eliasfano_test", "srcs": ["EliasFanoCodingTest.cpp"]},
            {"name": "event_count_test", "srcs": ["EventCountTest.cpp"]},
            {
                "name": "function_scheduler_test",
                "srcs": ["FunctionSchedulerTest.cpp"],
                "tags": ["BROKEN"],
            },
            {"name": "future_dag_test", "srcs": ["FutureDAGTest.cpp"]},
            {"name": "json_schema_test", "srcs": ["JSONSchemaTest.cpp"]},
            {"name": "lock_free_ring_buffer_test", "srcs": ["LockFreeRingBufferTest.cpp"]},
            {"name": "quotient_multiset_test", "srcs": ["QuotientMultiSetTest.cpp"]},
            {"name": "select64_test", "srcs": ["Select64Test.cpp"]},
            {
                "benchmark": 1,
                "name": "string_keyed_benchmark",
                "srcs": ["StringKeyedBenchmark.cpp"],
            },
            {"name": "stringkeyed_test", "srcs": ["StringKeyedTest.cpp"]},
            {"name": "test_util_test", "srcs": ["TestUtilTest.cpp"]},
            {"name": "tuple_ops_test", "srcs": ["TupleOpsTest.cpp"]},
        ],
        "external/farmhash/test/": [
            {"name": "farmhash_test", "srcs": ["farmhash_test.cpp"]},
        ],
        "fibers/test/": [
            {"benchmark": 1, "name": "fibers_benchmark", "srcs": ["FibersBenchmark.cpp"]},
            {"name": "fibers_test", "srcs": ["FibersTest.cpp"], "tags": ["BROKEN"]},
        ],
        "functional/test/": [
            {
                "name": "apply_tuple_test",
                "srcs": ["ApplyTupleTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "partial_test", "srcs": ["PartialTest.cpp"]},
        ],
        "futures/test/": [
            {"name": "barrier_test", "srcs": ["BarrierTest.cpp"]},
            {"name": "callback_lifetime_test", "srcs": ["CallbackLifetimeTest.cpp"]},
            {"name": "collect_test", "srcs": ["CollectTest.cpp"]},
            {"name": "context_test", "srcs": ["ContextTest.cpp"]},
            {"name": "core_test", "srcs": ["CoreTest.cpp"]},
            {"name": "ensure_test", "srcs": ["EnsureTest.cpp"]},
            {"name": "filter_test", "srcs": ["FilterTest.cpp"]},
            {"name": "future_splitter_test", "srcs": ["FutureSplitterTest.cpp"]},
            {
                "benchmark": 1,
                "name": "futures_benchmark",
                "srcs": ["Benchmark.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "future_test",
                "srcs": ["FutureTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "header_compile_test", "srcs": ["HeaderCompileTest.cpp"]},
            {"name": "interrupt_test", "srcs": ["InterruptTest.cpp"]},
            {"name": "map_test", "srcs": ["MapTest.cpp"]},
            {"name": "non_copyable_lambda_test", "srcs": ["NonCopyableLambdaTest.cpp"]},
            {"name": "poll_test", "srcs": ["PollTest.cpp"]},
            {"name": "promise_test", "srcs": ["PromiseTest.cpp"]},
            {"name": "reduce_test", "srcs": ["ReduceTest.cpp"]},
            {"name": "retrying_test", "srcs": ["RetryingTest.cpp"]},
            {"name": "self_destruct_test", "srcs": ["SelfDestructTest.cpp"]},
            {"name": "shared_promise_test", "srcs": ["SharedPromiseTest.cpp"]},
            {"name": "test_executor_test", "srcs": ["TestExecutorTest.cpp"]},
            {
                "hdrs": ["ThenCompileTest.h"],
                "name": "then_compile_test",
                "srcs": ["ThenCompileTest.cpp"],
            },
            {"name": "then_test", "srcs": ["ThenTest.cpp"]},
            {
                "name": "timekeeper_test",
                "srcs": ["TimekeeperTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "times_test", "srcs": ["TimesTest.cpp"]},
            {"name": "unwrap_test", "srcs": ["UnwrapTest.cpp"]},
            {"name": "via_test", "srcs": ["ViaTest.cpp"]},
            {"name": "wait_test", "srcs": ["WaitTest.cpp"]},
            {"name": "when_test", "srcs": ["WhenTest.cpp"]},
            {"name": "while_do_test", "srcs": ["WhileDoTest.cpp"]},
            {"name": "will_equal_test", "srcs": ["WillEqualTest.cpp"]},
            {
                "name": "window_test",
                "srcs": ["WindowTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
        ],
        "gen/test/": [
            {"name": "combine_test", "srcs": ["CombineTest.cpp"]},
            {
                "benchmark": 1,
                "name": "parallel_map_benchmark",
                "srcs": ["ParallelMapBenchmark.cpp"],
            },
            {"name": "parallel_map_test", "srcs": ["ParallelMapTest.cpp"]},
            {
                "benchmark": 1,
                "name": "parallel_benchmark",
                "srcs": ["ParallelBenchmark.cpp"],
                "hdrs": ["Bench.h"],
            },
            {"name": "parallel_test", "srcs": ["ParallelTest.cpp"]},
        ],
        "hash/test/": [
            {
                "benchmark": 1,
                "name": "checksum_benchmark",
                "srcs": ["ChecksumBenchmark.cpp"],
            },
            {"name": "checksum_test", "srcs": ["ChecksumTest.cpp"]},
            {"name": "farm_hash_test", "srcs": ["FarmHashTest.cpp"]},
            {
                "benchmark": 1,
                "name": "hash_benchmark",
                "srcs": ["HashBenchmark.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "hash_test", "srcs": ["HashTest.cpp"], "tags": ["WINDOWS_DISABLED"]},
            {"name": "spooky_hash_v1_test", "srcs": ["SpookyHashV1Test.cpp"]},
            {"name": "spooky_hash_v2_test", "srcs": ["SpookyHashV2Test.cpp"]},
        ],
        "io/async/ssl/test/": [{"name": "ssl_errors_test", "srcs": ["SSLErrorsTest.cpp"]}],
        "io/async/test/": [
            {
                "data": ["certs/"],
                "hdrs": ["AsyncSocketTest.h", "AsyncSSLSocketTest.h"],
                "name": "async_test",
                "srcs": [
                    "AsyncPipeTest.cpp",
                    "AsyncSocketExceptionTest.cpp",
                    "AsyncSocketTest.cpp",
                    "AsyncSocketTest2.cpp",
                    "AsyncSSLSocketTest.cpp",
                    "AsyncSSLSocketTest2.cpp",
                    "AsyncSSLSocketWriteTest.cpp",
                    "AsyncTransportTest.cpp",
                ],
                "tags": ["BROKEN"],
            },
            {"name": "async_timeout_test", "srcs": ["AsyncTimeoutTest.cpp"]},
            {
                "name": "AsyncUDPSocketTest",
                "srcs": ["AsyncUDPSocketTest.cpp"],
                "tags": ["WINDOWS_DISABLED", "APPLE_DISABLED"],
            },
            {"name": "DelayedDestructionTest", "srcs": ["DelayedDestructionTest.cpp"]},
            {
                "name": "DelayedDestructionBaseTest",
                "srcs": ["DelayedDestructionBaseTest.cpp"],
            },
            {"name": "DestructorCheckTest", "srcs": ["DestructorCheckTest.cpp"]},
            {"name": "EventBaseTest", "srcs": ["EventBaseTest.cpp"], "tags": ["BROKEN"]},
            {
                "name": "EventBaseLocalTest",
                "srcs": ["EventBaseLocalTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "HHWheelTimerTest", "srcs": ["HHWheelTimerTest.cpp"]},
            {
                "name": "HHWheelTimerSlowTests",
                "srcs": ["HHWheelTimerSlowTests.cpp"],
                "tags": ["SLOW"],
            },
            {
                "name": "NotificationQueueTest",
                "srcs": ["NotificationQueueTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "benchmark": 1,
                "hdrs": ["RequestContextHelper.h"],
                "name": "request_context_benchmark",
                "srcs": ["RequestContextBenchmark.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "RequestContextTest",
                "srcs": ["RequestContextTest.cpp"],
                "hdrs": ["RequestContextHelper.h"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "ScopedEventBaseThreadTest",
                "srcs": ["ScopedEventBaseThreadTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "data": ["certs/"],
                "name": "ssl_session_test",
                "srcs": ["SSLSessionTest.cpp"],
                "hdrs": ["AsyncSSLSocketTest.h"],
            },
            {
                "name": "writechain_test",
                "srcs": ["WriteChainAsyncTransportWrapperTest.cpp"],
            },
        ],
        "io/test/": [
            {"name": "iobuf_test", "srcs": ["IOBufTest.cpp"], "tags": ["WINDOWS_DISABLED"]},
            {"name": "iobuf_cursor_test", "srcs": ["IOBufCursorTest.cpp"]},
            {"name": "iobuf_queue_test", "srcs": ["IOBufQueueTest.cpp"]},
            {
                "name": "record_io_test",
                "srcs": ["RecordIOTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "ShutdownSocketSetTest",
                "srcs": ["ShutdownSocketSetTest.cpp"],
                "tags": ["HANGING"],
            },
        ],
        "lang/test/": [
            {"name": "lang_aligned_test", "srcs": ["AlignedTest.cpp"]},
            {"name": "lang_badge_test", "srcs": ["BadgeTest.cpp"]},
            {"name": "lang_bits_test", "srcs": ["BitsTest.cpp"]},
            {"name": "lang_byte_test", "srcs": ["ByteTest.cpp"]},
            {"name": "lang_c_string_test", "srcs": ["CStringTest.cpp"]},
            {"name": "lang_cast_test", "srcs": ["CastTest.cpp"]},
            {"name": "lang_checked_math_test", "srcs": ["CheckedMathTest.cpp"]},
            {"name": "lang_exception_test", "srcs": ["ExceptionTest.cpp"]},
            {"name": "lang_extern_test", "srcs": ["ExternTest.cpp"]},
            {"name": "lang_launder_test", "srcs": ["LaunderTest.cpp"]},
            {"name": "lang_ordering_test", "srcs": ["OrderingTest.cpp"]},
            {"name": "lang_pretty_test", "srcs": ["PrettyTest.cpp"]},
            {"name": "lang_propagate_const_test", "srcs": ["PropagateConstTest.cpp"]},
            {
                "name": "lang_r_value_reference_wrapper_test",
                "srcs": ["RValueReferenceWrapperTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "lang_safe_assert_test", "srcs": ["SafeAssertTest.cpp"]},
            {
                "benchmark": 1,
                "name": "lang_to_ascii_benchmark",
                "srcs": ["ToAsciiBench.cpp"],
            },
            {"name": "lang_to_ascii_test", "srcs": ["ToAsciiTest.cpp"]},
            {"name": "lang_type_info_test", "srcs": ["TypeInfoTest.cpp"]},
            {
                "name": "lang_uncaught_exceptions_test",
                "srcs": ["UncaughtExceptionsTest.cpp"],
            },
        ],
        "logging/test/": [
            {
                "name": "async_file_writer_test",
                "srcs": ["AsyncFileWriterTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "config_parser_test", "srcs": ["ConfigParserTest.cpp"]},
            {"name": "config_update_test", "srcs": ["ConfigUpdateTest.cpp"]},
            {
                "name": "file_handler_factory_test",
                "srcs": ["FileHandlerFactoryTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "glog_formatter_test", "srcs": ["GlogFormatterTest.cpp"]},
            {"name": "immediate_file_writer_test", "srcs": ["ImmediateFileWriterTest.cpp"]},
            {"name": "log_category_test", "srcs": ["LogCategoryTest.cpp"]},
            {"name": "logger_db_test", "srcs": ["LoggerDBTest.cpp"]},
            {
                "name": "logger_test",
                "srcs": ["LoggerTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "log_level_test", "srcs": ["LogLevelTest.cpp"]},
            {"name": "log_message_test", "srcs": ["LogMessageTest.cpp"]},
            {"name": "log_name_test", "srcs": ["LogNameTest.cpp"]},
            {"name": "log_stream_test", "srcs": ["LogStreamTest.cpp"]},
            {"name": "rate_limiter_test", "srcs": ["RateLimiterTest.cpp"]},
            {"name": "standard_log_handler_test", "srcs": ["StandardLogHandlerTest.cpp"]},
            {
                "hdrs": ["XlogHeader1.h", "XlogHeader2.h"],
                "name": "xlog_test",
                "srcs": ["XlogFile1.cpp", "XlogFile2.cpp", "XlogTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
        ],
        "memory/test/": [
            {"name": "arena_test", "srcs": ["ArenaTest.cpp"], "tags": ["WINDOWS_DISABLED"]},
            {
                "name": "reentrant_allocator_test",
                "srcs": ["ReentrantAllocatorTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "thread_cached_arena_test",
                "srcs": ["ThreadCachedArenaTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "mallctl_helper_test", "srcs": ["MallctlHelperTest.cpp"]},
            {
                "name": "uninitialized_memory_hacks_test",
                "srcs": ["UninitializedMemoryHacksTest.cpp"],
            },
        ],
        "net/detail/test/": [
            {
                "name": "socket_file_descriptor_map_test",
                "srcs": ["SocketFileDescriptorMapTest.cpp"],
            },
        ],
        "portability/test/": [
            {"name": "constexpr_test", "srcs": ["ConstexprTest.cpp"]},
            {"name": "filesystem_test", "srcs": ["FilesystemTest.cpp"]},
            {"name": "libgen-test", "srcs": ["LibgenTest.cpp"]},
            {"name": "openssl_portability_test", "srcs": ["OpenSSLPortabilityTest.cpp"]},
            {"name": "pthread_test", "srcs": ["PThreadTest.cpp"]},
            {"name": "time-test", "srcs": ["TimeTest.cpp"]},
        ],
        "ssl/test/": [{"name": "openssl_hash_test", "srcs": ["OpenSSLHashTest.cpp"]}],
        "stats/test/": [
            {"name": "buffered_stat_test", "srcs": ["BufferedStatTest.cpp"]},
            {
                "benchmark": 1,
                "name": "digest_builder_benchmark",
                "srcs": ["DigestBuilderBenchmark.cpp"],
            },
            {"name": "digest_builder_test", "srcs": ["DigestBuilderTest.cpp"]},
            {
                "benchmark": 1,
                "name": "histogram_benchmark",
                "srcs": ["HistogramBenchmark.cpp"],
            },
            {"name": "histogram_test", "srcs": ["HistogramTest.cpp"]},
            {
                "benchmark": 1,
                "name": "quantile_histogram_benchmark",
                "srcs": ["QuantileHistogramBenchmark.cpp"],
            },
            {"name": "quantile_estimator_test", "srcs": ["QuantileEstimatorTest.cpp"]},
            {"name": "sliding_window_test", "srcs": ["SlidingWindowTest.cpp"]},
            {"benchmark": 1, "name": "tdigest_benchmark", "srcs": ["TDigestBenchmark.cpp"]},
            {"name": "tdigest_test", "srcs": ["TDigestTest.cpp"]},
            {"name": "timeseries_histogram_test", "srcs": ["TimeseriesHistogramTest.cpp"]},
            {"name": "timeseries_test", "srcs": ["TimeSeriesTest.cpp"]},
        ],
        "synchronization/detail/test/": [
            {"name": "hardware_test", "srcs": ["HardwareTest.cpp"]},
        ],
        "synchronization/test/": [
            {
                "benchmark": 1,
                "name": "baton_benchmark",
                "srcs": ["BatonBenchmark.cpp"],
                "hdrs": ["BatonTestHelpers.h"],
            },
            {
                "name": "baton_test",
                "srcs": ["BatonTest.cpp"],
                "hdrs": ["BatonTestHelpers.h"],
            },
            {"name": "call_once_test", "srcs": ["CallOnceTest.cpp"]},
            {
                "name": "lifo_sem_test",
                "srcs": ["LifoSemTests.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "relaxed_atomic_test",
                "srcs": ["RelaxedAtomicTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "rw_spin_lock_test", "srcs": ["RWSpinLockTest.cpp"]},
            {
                "name": "semaphore_test",
                "srcs": ["SemaphoreTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "atomic_struct_test", "srcs": ["AtomicStructTest.cpp"]},
            {"name": "small_locks_test", "srcs": ["SmallLocksTest.cpp"]},
            {"name": "atomic_util_test", "srcs": ["AtomicUtilTest.cpp"]},
        ],
        "system/test/": [
            {"name": "memory_mapping_test", "srcs": ["MemoryMappingTest.cpp"]},
            {"name": "shell_test", "srcs": ["ShellTest.cpp"]},
            {"name": "thread_id_test", "srcs": ["ThreadIdTest.cpp"]},
            {
                "name": "thread_name_test",
                "srcs": ["ThreadNameTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
        ],
        "test/": [
            {"name": "ahm_int_stress_test", "srcs": ["AHMIntStressTest.cpp"]},
            {"name": "arena_smartptr_test", "srcs": ["ArenaSmartPtrTest.cpp"]},
            {
                "benchmark": 1,
                "name": "ascii_case_insensitive_benchmark",
                "srcs": ["AsciiCaseInsensitiveBenchmark.cpp"],
            },
            {"name": "ascii_check_test", "srcs": ["AsciiCaseInsensitiveTest.cpp"]},
            {"name": "atomic_hash_array_test", "srcs": ["AtomicHashArrayTest.cpp"]},
            {
                "name": "atomic_hash_map_test",
                "srcs": ["AtomicHashMapTest.cpp"],
                "tags": ["HANGING"],
            },
            {"name": "atomic_linked_list_test", "srcs": ["AtomicLinkedListTest.cpp"]},
            {"name": "atomic_unordered_map_test", "srcs": ["AtomicUnorderedMapTest.cpp"]},
            {"name": "base64_test", "srcs": ["base64_test.cpp"]},
            {
                "name": "clock_gettime_wrappers_test",
                "srcs": ["ClockGettimeWrappersTest.cpp"],
            },
            {"name": "concurrent_bit_set_test", "srcs": ["ConcurrentBitSetTest.cpp"]},
            {
                "benchmark": 1,
                "name": "concurrent_skip_list_benchmark",
                "srcs": ["ConcurrentSkipListBenchmark.cpp"],
            },
            {"name": "concurrent_skip_list_test", "srcs": ["ConcurrentSkipListTest.cpp"]},
            {"name": "conv_test", "srcs": ["ConvTest.cpp"], "tags": ["WINDOWS_DISABLED"]},
            {"name": "cpu_id_test", "srcs": ["CpuIdTest.cpp"]},
            {"name": "demangle_test", "srcs": ["DemangleTest.cpp"]},
            {
                "name": "deterministic_schedule_test",
                "srcs": ["DeterministicScheduleTest.cpp"],
            },
            {"name": "discriminated_ptr_test", "srcs": ["DiscriminatedPtrTest.cpp"]},
            {
                "name": "dynamic_test",
                "srcs": ["DynamicTest.cpp"],
                "hdrs": ["ComparisonOperatorTestUtil.h"],
            },
            {"name": "dynamic_converter_test", "srcs": ["DynamicConverterTest.cpp"]},
            {"name": "dynamic_other_test", "srcs": ["DynamicOtherTest.cpp"]},
            {"name": "endian_test", "srcs": ["EndianTest.cpp"]},
            {"name": "exception_test", "srcs": ["ExceptionTest.cpp"]},
            {
                "benchmark": 1,
                "name": "exception_wrapper_benchmark",
                "srcs": ["ExceptionWrapperBenchmark.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "exception_wrapper_test",
                "srcs": ["ExceptionWrapperTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "expected_test", "srcs": ["ExpectedTest.cpp"]},
            {
                "benchmark": 1,
                "hdrs": ["FBStringTestBenchmarks.cpp.h"],
                "name": "fbstring_benchmark",
                "srcs": ["FBStringBenchmark.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "fbstring_test",
                "srcs": ["FBStringTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "benchmark": 1,
                "hdrs": ["FBVectorBenchmarks.cpp.h"],
                "name": "fbvector_benchmark",
                "srcs": ["FBVectorBenchmark.cpp"],
            },
            {
                "name": "fbvector_test",
                "srcs": ["FBVectorTest.cpp"],
                "hdrs": ["FBVectorTests.cpp.h"],
            },
            {"name": "file_test", "srcs": ["FileTest.cpp"]},
            {"name": "file_util_test", "srcs": ["FileUtilTest.cpp"]},
            {
                "benchmark": 1,
                "name": "fingerprint_benchmark",
                "srcs": ["FingerprintBenchmark.cpp"],
            },
            {"name": "fingerprint_test", "srcs": ["FingerprintTest.cpp"]},
            {"name": "fixed_string_test", "srcs": ["FixedStringTest.cpp"]},
            {"name": "format_other_test", "srcs": ["FormatOtherTest.cpp"]},
            {"benchmark": 1, "name": "format_benchmark", "srcs": ["FormatBenchmark.cpp"]},
            {"name": "format_test", "srcs": ["FormatTest.cpp"]},
            {"name": "function_test", "srcs": ["FunctionTest.cpp"], "tags": ["BROKEN"]},
            {
                "benchmark": 1,
                "name": "function_ref_benchmark",
                "srcs": ["FunctionRefBenchmark.cpp"],
            },
            {"name": "function_ref_test", "srcs": ["FunctionRefTest.cpp"]},
            {"name": "futex_test", "srcs": ["FutexTest.cpp"]},
            {"name": "glog_test", "srcs": ["GLogTest.cpp"]},
            {"name": "group_varint_test", "srcs": ["GroupVarintTest.cpp"]},
            {"name": "group_varint_test_ssse3", "srcs": ["GroupVarintTest.cpp"]},
            {"name": "iterators_test", "srcs": ["IteratorsTest.cpp"]},
            {"name": "indestructible_test", "srcs": ["IndestructibleTest.cpp"]},
            {
                "name": "indexed_mem_pool_test",
                "srcs": ["IndexedMemPoolTest.cpp"],
                "tags": ["BROKEN"],
            },
            {"name": "json_test", "srcs": ["JsonTest.cpp"], "tags": ["WINDOWS_DISABLED"]},
            {"benchmark": 1, "name": "json_benchmark", "srcs": ["JsonBenchmark.cpp"]},
            {"name": "json_pointer_test", "srcs": ["json_pointer_test.cpp"]},
            {"name": "json_patch_test", "srcs": ["json_patch_test.cpp"]},
            {"name": "json_other_test", "srcs": ["JsonOtherTest.cpp"]},
            {"name": "lazy_test", "srcs": ["LazyTest.cpp"]},
            {"name": "locks_test", "srcs": ["SpinLockTest.cpp"]},
            {"name": "math_test", "srcs": ["MathTest.cpp"]},
            {
                "name": "map_util_test",
                "srcs": ["MapUtilTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "memcpy_test", "srcs": ["MemcpyTest.cpp"]},
            {"name": "memory_idler_test", "srcs": ["MemoryIdlerTest.cpp"]},
            {
                "name": "memory_test",
                "srcs": ["MemoryTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "move_wrapper_test", "srcs": ["MoveWrapperTest.cpp"]},
            {"name": "mpmc_pipeline_test", "srcs": ["MPMCPipelineTest.cpp"]},
            {"name": "mpmc_queue_test", "srcs": ["MPMCQueueTest.cpp"], "tags": ["SLOW"]},
            {
                "name": "network_address_test",
                "srcs": [
                    "IPAddressTest.cpp",
                    "MacAddressTest.cpp",
                    "SocketAddressTest.cpp",
                ],
                "tags": ["HANGING"],
            },
            {"name": "optional_test", "srcs": ["OptionalTest.cpp"]},
            {
                "name": "packed_sync_ptr_test",
                "srcs": ["PackedSyncPtrTest.cpp"],
                "tags": ["HANGING"],
            },
            {"name": "padded_test", "srcs": ["PaddedTest.cpp"]},
            {"name": "portability_test", "srcs": ["PortabilityTest.cpp"]},
            {
                "benchmark": 1,
                "name": "producer_consumer_queue_benchmark",
                "srcs": ["ProducerConsumerQueueBenchmark.cpp"],
                "tags": ["APPLE_DISABLED"],
            },
            {
                "name": "producer_consumer_queue_test",
                "srcs": ["ProducerConsumerQueueTest.cpp"],
                "tags": ["SLOW"],
            },
            {
                "benchmark": 1,
                "name": "range_find_benchmark",
                "srcs": ["RangeFindBenchmark.cpp"],
            },
            {"name": "random_test", "srcs": ["RandomTest.cpp"]},
            {"name": "range_test", "srcs": ["RangeTest.cpp"]},
            {
                "name": "replaceable_test",
                "srcs": ["ReplaceableTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "scope_guard_test",
                "srcs": ["ScopeGuardTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "singleton_test_global", "srcs": ["SingletonTestGlobal.cpp"]},
            {
                "name": "small_vector_test",
                "srcs": ["small_vector_test.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "sorted_vector_types_test", "srcs": ["sorted_vector_test.cpp"]},
            {
                "benchmark": 1,
                "name": "string_benchmark",
                "srcs": ["StringBenchmark.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "string_test",
                "srcs": ["StringTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "benchmark": 1,
                "name": "synchronized_benchmark",
                "srcs": ["SynchronizedBenchmark.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "synchronized_test",
                "srcs": ["SynchronizedTest.cpp"],
                "hdrs": ["SynchronizedTestLib.h", "SynchronizedTestLib-inl.h"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "thread_cached_int_test",
                "srcs": ["ThreadCachedIntTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {
                "name": "thread_local_test",
                "srcs": ["ThreadLocalTest.cpp"],
                "tags": ["WINDOWS_DISABLED"],
            },
            {"name": "timeout_queue_test", "srcs": ["TimeoutQueueTest.cpp"]},
            {
                "name": "token_bucket_test",
                "srcs": ["TokenBucketTest.cpp"],
                "hdrs": ["TokenBucketTest.h"],
            },
            {"name": "traits_test", "srcs": ["TraitsTest.cpp"]},
            {"name": "try_test", "srcs": ["TryTest.cpp"], "tags": ["WINDOWS_DISABLED"]},
            {"name": "unit_test", "srcs": ["UnitTest.cpp"]},
            {"benchmark": 1, "name": "uri_benchmark", "srcs": ["UriBenchmark.cpp"]},
            {"name": "uri_test", "srcs": ["UriTest.cpp"]},
            {"name": "varint_test", "srcs": ["VarintTest.cpp"]},
            {
                "name": "singleton_thread_local_test",
                "srcs": ["SingletonThreadLocalTest.cpp"],
            },
        ],
    }
